Job 15user mentor
ITer-FR/BookMyMentor pull request #23
Opened 2021-05-18 19:40 UTC by Dimitri-Basseguy

cette fois sa passe ?

2021-05-19 08:48 UTC, ReCoN-96 requested changes
On a un probléme au niveau de swagger, lorsque l'on va sur localhost/docs  ui swagger ne fonctionne pas et nous avons cela en résultat 
![bugdimitri](https://user-images.githubusercontent.com/48048474/118783745-a69be200-b88f-11eb-8f13-1e7e4c943df0.png)

De plus j'ai remarqué qu'il y a une erreur concernant la serialization dans la console (peut etre est-ce lié) 
![dimitribug2](https://user-images.githubusercontent.com/48048474/118783852-c03d2980-b88f-11eb-8efd-47793df7b279.png)

2021-05-19 09:47 UTC, Dimitri-Basseguy commented
Surement quand j'ai dit à apiPlatForm de rester en mode Json pure et stopper le JsonLD., Si vous testez les routes API vous recevez bien le Json ?

2021-05-19 12:42 UTC, ReCoN-96 commented
> Surement quand j'ai dit à apiPlatForm de rester en mode Json pure et stopper le JsonLD., Si vous testez les routes API vous recevez bien le Json ?

Et c'est possible de faire réapparaitre l'ui de swagger car sans ça je ne sais pas comment recupèrer les routes

2021-05-19 13:00 UTC, Dimitri-Basseguy commented
normalement les routes sont les mêmes (faut relancer les fixtures avant quand même)
tonlocalhost/projet/mentors
tonlocalhost/projet/mentors/{id}

2021-05-19 19:00 UTC, Dimitri-Basseguy commented
ha merde chez moi ca foire aussi...

2021-05-26 09:15 UTC, VirginieBouvarel approved these changes

2021-06-02 12:47 UTC, ReCoN-96 approved these changes

2024-05-16 08:44 UTC, closed without merging